version = 1

[[annotations]]
path = [
    "docs/**",
    ".mvn/README.md",
    ".mvn/wrapper/maven-wrapper.properties",
    ".gitattributes",
    ".gitignore",
    ".idea/**",
    "jdbc-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor",
    "jdbc-processor-spec/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension",
    "NOTICE",
    "mvnw",
    "mvnw.cmd"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "Apache-2.0"



